#!/usr/bin/env zsh
# Install dotfiles for ubuntu

if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="bin,nvim,tmux,vim,zsh"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
