vim.cmd('source ' .. '~/.config/nvim/lua/ickoxii/templates.vim')
-- require("ickoxii.templates")
require("ickoxii.options")
require("ickoxii.lazy")
require("ickoxii.remaps")
require("ickoxii.pandoc")
